version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
      time: "14:00"
    open-pull-requests-limit: 100
    insecure-external-code-execution: allow
    registries: "*"
    groups:
      minor-gem-update:
        update-types:
          - "minor"
      patch-gem-update:
        update-types:
          - "patch"
