inherit_from:
  - http://shopify.github.io/ruby-style-guide/rubocop.yml

AllCops:
  Exclude:
    - 'tmp/**/*'
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Exclude:
    - 'test/**/*'

Style/GlobalVars:
  Exclude:
    - 'ext/rotoscope/extconf.rb'
