inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  Exclude:
    - 'tmp/**/*'
    - 'test/memory_test.rb'
    - 'test/safety_test.rb'

Layout/LineLength:
  Exclude:
    - 'test/**/*'

Naming/MethodName:
  Exclude:
    - 'test/**/*'

Style/GlobalVars:
  Exclude:
    - 'ext/rotoscope/extconf.rb'
