inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  Exclude:
    - 'tmp/**/*'

Metrics/LineLength:
  Exclude:
    - 'test/**/*'

Style/GlobalVars:
  Exclude:
    - 'ext/rotoscope/extconf.rb'
